### ISSUE TITLE
Docker container exits by itself

### ISSUE THREAD

**Issue by volodymyrzuyev** [csgofloat/inspect#158]
The docker container for self hosted repo shuts down after it is created. I'm 99% sure that it's user error, but I followed the docs to the best of my abilities

**Comment by nkowalchuk301** [comment]
This was also happening with me, I re built it with node but still get the same issues.

**Comment by volodymyrzuyev** [comment]
From my research, it's probably a problem with Postgres. I probably have been setting it up wrong. Will look into it a bit latter

**Comment by nkowalchuk301** [comment]
Ohne pixel server is also not able to return requests from API... something is going on.

**Comment by volodymyrzuyev** [comment]
So i figured it out. The problem was with postgres setup. Through trail and error I used this docker-compose.yml to get it up and running 
```
version: '3.1'
services:

db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  float:
    image: step7750/csgofloat:master
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - /path/to/config:/config
```

and this in the config.js file
`
'database_url': 'postgres://postgres:example@<lan ip adress>:5432/postgres?sslmode=disable',
`
